#!/usr/bin/bash

# Non-interactive env var
export QT_STYLE_OVERRIDE=kvantum

# Command overrides (also non-interactive)
alias make='make -j8'
alias ninja='ninja -j8'

# Make NVM available non-interactively
source /usr/share/nvm/init-nvm.sh

# If not running interactively, don't do anything else
[[ $- != *i* ]] && return

# Command overrides (interactive)
alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -h --color=auto --group-directories-first -l'
alias la='ls -h --color=auto --group-directories-first -A'
alias lla='ls -h --color=auto --group-directories-first -l -A'
alias nano='nano -wzA'
alias unrar='unrar x'
alias ip='ip -c'
alias gulp='gulp --color'
alias radeontop='radeontop --color'

# Aliases
alias large-files='sudo du --si --one-file-system --threshold 1GB'
alias list-npm-globals="npm ls -g --depth=0 | tail -n +2 | sed -E 's/.*─ (.*?)@.*/\1/g' | tr '\n' ' '"
alias update-npm-globals='sudo npm install -g $(list-npm-globals)'
alias upd='trizen -Syu'
alias gpu-high-perf='echo "high" | sudo tee /sys/class/drm/card1/device/power_dpm_force_performance_level'
alias open="xdg-open"
alias netscan="sudo arp-scan --localnet --interface=enp6s0"

# Enable color
export BAT_THEME="OneHalfDark"

# Config
export TERM=konsole
export EDITOR=vim
# Don't define VISUAL; some programs do dumb things with it (like git)
#export VISUAL=atom
export BROWSER=chromium

# Path
PATH=$HOME/Scripts/path-overrides:$PATH:$HOME/Scripts:/opt/jetbrains-toolbox/scripts
export PATH

PROMPT_COMMAND="PS1=\"\$($HOME/.gen-ps1.sh $0)\""

# Unlimited history
HISTSIZE=-1
HISTFILESIZE=-1

# Disable CTRL-S/CTRL-Q output on/off commands
stty -ixon

# Git auto completion
source /usr/share/bash-completion/completions/git

# This would start X when logging in on tty1, except the login manager does it for us
#[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
