filetype plugin indent on

set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set modeline
set backspace=indent,eol,start

set number
highlight LineNr ctermbg=Black

syntax on

" Backspace in normal mode
nnoremap <bs> d1<Left>
" CTRL-D to delete line
inoremap <C-D> <Esc>dd<Insert>
nnoremap <C-D> dd
" CTRL-Z to undo
inoremap <C-Z> <Esc>u<Insert>
nnoremap <C-Z> u
" CTRL-Y to redo
inoremap <C-Y> <Esc><C-R><Insert>
nnoremap <C-Y> <C-R>
" CTRL-S to save
inoremap <C-S> <Esc>:w<Enter><Insert>
nnoremap <C-S> :w<Enter>
" CTRL-arrow to move up down lines
inoremap [1;5A <Esc>k<Insert>
inoremap [1;5B <Esc>j<Insert>
nnoremap [1;5A k
nnoremap [1;5B j
" CTRL-arrow to move word by word
" CTRL-Left
inoremap [1;5D <Esc>b<Insert>
nnoremap [1;5D b
" CTRL-Right
inoremap [1;5C <Esc>el<Insert>
nnoremap [1;5C el
" CTRL-End goes to end of file
inoremap [1;5F <Esc>G<Insert>
nnoremap [1;5F G
" CTRL-Home goes to start of file
inoremap [1;5H <Esc>gg<Insert>
nnoremap [1;5H gg

